/*
 * generated by Xtext
 */
package com.polimi.ase.concretesyntax.xtext.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;

public class AbstractSmartCityValidator extends org.eclipse.xtext.validation.AbstractDeclarativeValidator {

	@Override
	protected List<EPackage> getEPackages() {
	    List<EPackage> result = new ArrayList<EPackage>();
	    result.add(com.polimi.ase.concretesyntax.xtext.smartCity.SmartCityPackage.eINSTANCE);
		return result;
	}
}
