/*
 * generated by Xtext
 */
package com.polimi.ase.concretesyntax.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SmartCityUiModule extends com.polimi.ase.concretesyntax.xtext.ui.AbstractSmartCityUiModule {
	public SmartCityUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
