/*
* generated by Xtext
*/
package com.polimi.ase.concretesyntax.xtext.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SmartCityGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class SmartCityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SmartCity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cProvidersAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cProvidersProviderParserRuleCall_0_0 = (RuleCall)cProvidersAssignment_0.eContents().get(0);
		private final Assignment cDataSourcesAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDataSourcesDataSourceParserRuleCall_1_0 = (RuleCall)cDataSourcesAssignment_1.eContents().get(0);
		
		////import "platform:/resource/com.polimi.ase.smartcity_b/model/SmartCity.ecore"
		// //extension 'scity'
		// SmartCity:
		//	providers+=Provider+ dataSources+=DataSource*;
		public ParserRule getRule() { return rule; }

		//providers+=Provider+ dataSources+=DataSource*
		public Group getGroup() { return cGroup; }

		//providers+=Provider+
		public Assignment getProvidersAssignment_0() { return cProvidersAssignment_0; }

		//Provider
		public RuleCall getProvidersProviderParserRuleCall_0_0() { return cProvidersProviderParserRuleCall_0_0; }

		//dataSources+=DataSource*
		public Assignment getDataSourcesAssignment_1() { return cDataSourcesAssignment_1; }

		//DataSource
		public RuleCall getDataSourcesDataSourceParserRuleCall_1_0() { return cDataSourcesDataSourceParserRuleCall_1_0; }
	}

	public class ProviderElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Provider");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNewsSiteParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cHighwayParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cPublicTransportParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cProvinceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cCountyParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final RuleCall cMunicipalityParserRuleCall_5 = (RuleCall)cAlternatives.eContents().get(5);
		
		//Provider:
		//	NewsSite | Highway | PublicTransport | Province | County | Municipality;
		public ParserRule getRule() { return rule; }

		//NewsSite | Highway | PublicTransport | Province | County | Municipality
		public Alternatives getAlternatives() { return cAlternatives; }

		//NewsSite
		public RuleCall getNewsSiteParserRuleCall_0() { return cNewsSiteParserRuleCall_0; }

		//Highway
		public RuleCall getHighwayParserRuleCall_1() { return cHighwayParserRuleCall_1; }

		//PublicTransport
		public RuleCall getPublicTransportParserRuleCall_2() { return cPublicTransportParserRuleCall_2; }

		//Province
		public RuleCall getProvinceParserRuleCall_3() { return cProvinceParserRuleCall_3; }

		//County
		public RuleCall getCountyParserRuleCall_4() { return cCountyParserRuleCall_4; }

		//Municipality
		public RuleCall getMunicipalityParserRuleCall_5() { return cMunicipalityParserRuleCall_5; }
	}

	public class NewsSiteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "NewsSite");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cNewsSiteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourcesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSourcesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSourcesDataSourceCrossReference_4_0 = (CrossReference)cSourcesAssignment_4.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_4_0_1 = (RuleCall)cSourcesDataSourceCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSourcesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSourcesDataSourceCrossReference_5_1_0 = (CrossReference)cSourcesAssignment_5_1.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cSourcesDataSourceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//NewsSite:
		//	"NewsSite " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
		public ParserRule getRule() { return rule; }

		//"NewsSite " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}"
		public Group getGroup() { return cGroup; }

		//"NewsSite "
		public Keyword getNewsSiteKeyword_0() { return cNewsSiteKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//" {"
		public Keyword getSpaceLeftCurlyBracketKeyword_2() { return cSpaceLeftCurlyBracketKeyword_2; }

		//"sources "
		public Keyword getSourcesKeyword_3() { return cSourcesKeyword_3; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_4() { return cSourcesAssignment_4; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_4_0() { return cSourcesDataSourceCrossReference_4_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_4_0_1() { return cSourcesDataSourceIDTerminalRuleCall_4_0_1; }

		//("," sources+=[DataSource])*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_5_1() { return cSourcesAssignment_5_1; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_5_1_0() { return cSourcesDataSourceCrossReference_5_1_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_5_1_0_1() { return cSourcesDataSourceIDTerminalRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class HighwayElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Highway");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHighwayKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourcesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSourcesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSourcesDataSourceCrossReference_4_0 = (CrossReference)cSourcesAssignment_4.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_4_0_1 = (RuleCall)cSourcesDataSourceCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSourcesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSourcesDataSourceCrossReference_5_1_0 = (CrossReference)cSourcesAssignment_5_1.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cSourcesDataSourceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Highway:
		//	"Highway " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
		public ParserRule getRule() { return rule; }

		//"Highway " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}"
		public Group getGroup() { return cGroup; }

		//"Highway "
		public Keyword getHighwayKeyword_0() { return cHighwayKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//" {"
		public Keyword getSpaceLeftCurlyBracketKeyword_2() { return cSpaceLeftCurlyBracketKeyword_2; }

		//"sources "
		public Keyword getSourcesKeyword_3() { return cSourcesKeyword_3; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_4() { return cSourcesAssignment_4; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_4_0() { return cSourcesDataSourceCrossReference_4_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_4_0_1() { return cSourcesDataSourceIDTerminalRuleCall_4_0_1; }

		//("," sources+=[DataSource])*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_5_1() { return cSourcesAssignment_5_1; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_5_1_0() { return cSourcesDataSourceCrossReference_5_1_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_5_1_0_1() { return cSourcesDataSourceIDTerminalRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class PublicTransportElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PublicTransport");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPublicTransportKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourcesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSourcesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSourcesDataSourceCrossReference_4_0 = (CrossReference)cSourcesAssignment_4.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_4_0_1 = (RuleCall)cSourcesDataSourceCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSourcesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSourcesDataSourceCrossReference_5_1_0 = (CrossReference)cSourcesAssignment_5_1.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cSourcesDataSourceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//PublicTransport:
		//	"PublicTransport " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
		public ParserRule getRule() { return rule; }

		//"PublicTransport " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}"
		public Group getGroup() { return cGroup; }

		//"PublicTransport "
		public Keyword getPublicTransportKeyword_0() { return cPublicTransportKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//" {"
		public Keyword getSpaceLeftCurlyBracketKeyword_2() { return cSpaceLeftCurlyBracketKeyword_2; }

		//"sources "
		public Keyword getSourcesKeyword_3() { return cSourcesKeyword_3; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_4() { return cSourcesAssignment_4; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_4_0() { return cSourcesDataSourceCrossReference_4_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_4_0_1() { return cSourcesDataSourceIDTerminalRuleCall_4_0_1; }

		//("," sources+=[DataSource])*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_5_1() { return cSourcesAssignment_5_1; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_5_1_0() { return cSourcesDataSourceCrossReference_5_1_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_5_1_0_1() { return cSourcesDataSourceIDTerminalRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class ProvinceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Province");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProvinceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourcesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSourcesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSourcesDataSourceCrossReference_4_0 = (CrossReference)cSourcesAssignment_4.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_4_0_1 = (RuleCall)cSourcesDataSourceCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSourcesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSourcesDataSourceCrossReference_5_1_0 = (CrossReference)cSourcesAssignment_5_1.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cSourcesDataSourceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Province:
		//	"Province " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
		public ParserRule getRule() { return rule; }

		//"Province " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}"
		public Group getGroup() { return cGroup; }

		//"Province "
		public Keyword getProvinceKeyword_0() { return cProvinceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//" {"
		public Keyword getSpaceLeftCurlyBracketKeyword_2() { return cSpaceLeftCurlyBracketKeyword_2; }

		//"sources "
		public Keyword getSourcesKeyword_3() { return cSourcesKeyword_3; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_4() { return cSourcesAssignment_4; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_4_0() { return cSourcesDataSourceCrossReference_4_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_4_0_1() { return cSourcesDataSourceIDTerminalRuleCall_4_0_1; }

		//("," sources+=[DataSource])*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_5_1() { return cSourcesAssignment_5_1; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_5_1_0() { return cSourcesDataSourceCrossReference_5_1_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_5_1_0_1() { return cSourcesDataSourceIDTerminalRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class CountyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "County");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCountyKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourcesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSourcesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSourcesDataSourceCrossReference_4_0 = (CrossReference)cSourcesAssignment_4.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_4_0_1 = (RuleCall)cSourcesDataSourceCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSourcesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSourcesDataSourceCrossReference_5_1_0 = (CrossReference)cSourcesAssignment_5_1.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cSourcesDataSourceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//County:
		//	"County " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
		public ParserRule getRule() { return rule; }

		//"County " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}"
		public Group getGroup() { return cGroup; }

		//"County "
		public Keyword getCountyKeyword_0() { return cCountyKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//" {"
		public Keyword getSpaceLeftCurlyBracketKeyword_2() { return cSpaceLeftCurlyBracketKeyword_2; }

		//"sources "
		public Keyword getSourcesKeyword_3() { return cSourcesKeyword_3; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_4() { return cSourcesAssignment_4; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_4_0() { return cSourcesDataSourceCrossReference_4_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_4_0_1() { return cSourcesDataSourceIDTerminalRuleCall_4_0_1; }

		//("," sources+=[DataSource])*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_5_1() { return cSourcesAssignment_5_1; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_5_1_0() { return cSourcesDataSourceCrossReference_5_1_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_5_1_0_1() { return cSourcesDataSourceIDTerminalRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class MunicipalityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Municipality");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMunicipalityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cSourcesKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cSourcesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cSourcesDataSourceCrossReference_4_0 = (CrossReference)cSourcesAssignment_4.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_4_0_1 = (RuleCall)cSourcesDataSourceCrossReference_4_0.eContents().get(1);
		private final Group cGroup_5 = (Group)cGroup.eContents().get(5);
		private final Keyword cCommaKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Assignment cSourcesAssignment_5_1 = (Assignment)cGroup_5.eContents().get(1);
		private final CrossReference cSourcesDataSourceCrossReference_5_1_0 = (CrossReference)cSourcesAssignment_5_1.eContents().get(0);
		private final RuleCall cSourcesDataSourceIDTerminalRuleCall_5_1_0_1 = (RuleCall)cSourcesDataSourceCrossReference_5_1_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//Municipality:
		//	"Municipality " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
		public ParserRule getRule() { return rule; }

		//"Municipality " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}"
		public Group getGroup() { return cGroup; }

		//"Municipality "
		public Keyword getMunicipalityKeyword_0() { return cMunicipalityKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//" {"
		public Keyword getSpaceLeftCurlyBracketKeyword_2() { return cSpaceLeftCurlyBracketKeyword_2; }

		//"sources "
		public Keyword getSourcesKeyword_3() { return cSourcesKeyword_3; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_4() { return cSourcesAssignment_4; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_4_0() { return cSourcesDataSourceCrossReference_4_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_4_0_1() { return cSourcesDataSourceIDTerminalRuleCall_4_0_1; }

		//("," sources+=[DataSource])*
		public Group getGroup_5() { return cGroup_5; }

		//","
		public Keyword getCommaKeyword_5_0() { return cCommaKeyword_5_0; }

		//sources+=[DataSource]
		public Assignment getSourcesAssignment_5_1() { return cSourcesAssignment_5_1; }

		//[DataSource]
		public CrossReference getSourcesDataSourceCrossReference_5_1_0() { return cSourcesDataSourceCrossReference_5_1_0; }

		//ID
		public RuleCall getSourcesDataSourceIDTerminalRuleCall_5_1_0_1() { return cSourcesDataSourceIDTerminalRuleCall_5_1_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class DataSourceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DataSource");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cDataSourceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cSpaceLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cDataAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cDataDataParserRuleCall_3_0 = (RuleCall)cDataAssignment_3.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//DataSource:
		//	"DataSource " name=ID " {" data+=Data+ "}";
		public ParserRule getRule() { return rule; }

		//"DataSource " name=ID " {" data+=Data+ "}"
		public Group getGroup() { return cGroup; }

		//"DataSource "
		public Keyword getDataSourceKeyword_0() { return cDataSourceKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//" {"
		public Keyword getSpaceLeftCurlyBracketKeyword_2() { return cSpaceLeftCurlyBracketKeyword_2; }

		//data+=Data+
		public Assignment getDataAssignment_3() { return cDataAssignment_3; }

		//Data
		public RuleCall getDataDataParserRuleCall_3_0() { return cDataDataParserRuleCall_3_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class MetadataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Metadata");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLocationParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cUpdateFreqParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIssuedDateParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//Metadata:
		//	Location | UpdateFreq | IssuedDate;
		public ParserRule getRule() { return rule; }

		//Location | UpdateFreq | IssuedDate
		public Alternatives getAlternatives() { return cAlternatives; }

		//Location
		public RuleCall getLocationParserRuleCall_0() { return cLocationParserRuleCall_0; }

		//UpdateFreq
		public RuleCall getUpdateFreqParserRuleCall_1() { return cUpdateFreqParserRuleCall_1; }

		//IssuedDate
		public RuleCall getIssuedDateParserRuleCall_2() { return cIssuedDateParserRuleCall_2; }
	}

	public class IssuedDateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IssuedDate");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIssuedDateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cDateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cDateAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDateSTRINGTerminalRuleCall_2_0 = (RuleCall)cDateAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//IssuedDate:
		//	"IssuedDate {" "date" date=STRING "}";
		public ParserRule getRule() { return rule; }

		//"IssuedDate {" "date" date=STRING "}"
		public Group getGroup() { return cGroup; }

		//"IssuedDate {"
		public Keyword getIssuedDateKeyword_0() { return cIssuedDateKeyword_0; }

		//"date"
		public Keyword getDateKeyword_1() { return cDateKeyword_1; }

		//date=STRING
		public Assignment getDateAssignment_2() { return cDateAssignment_2; }

		//STRING
		public RuleCall getDateSTRINGTerminalRuleCall_2_0() { return cDateSTRINGTerminalRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class LocationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Location");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cLocationKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLatitudeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cLatitudeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cLatitudeSTRINGTerminalRuleCall_2_0 = (RuleCall)cLatitudeAssignment_2.eContents().get(0);
		private final Keyword cLongitudeKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cLongitudeAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cLongitudeSTRINGTerminalRuleCall_4_0 = (RuleCall)cLongitudeAssignment_4.eContents().get(0);
		private final Keyword cRegionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cRegionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cRegionSTRINGTerminalRuleCall_6_0 = (RuleCall)cRegionAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Location:
		//	"Location {" "latitude" latitude=STRING "longitude" longitude=STRING "region" region=STRING "}";
		public ParserRule getRule() { return rule; }

		//"Location {" "latitude" latitude=STRING "longitude" longitude=STRING "region" region=STRING "}"
		public Group getGroup() { return cGroup; }

		//"Location {"
		public Keyword getLocationKeyword_0() { return cLocationKeyword_0; }

		//"latitude"
		public Keyword getLatitudeKeyword_1() { return cLatitudeKeyword_1; }

		//latitude=STRING
		public Assignment getLatitudeAssignment_2() { return cLatitudeAssignment_2; }

		//STRING
		public RuleCall getLatitudeSTRINGTerminalRuleCall_2_0() { return cLatitudeSTRINGTerminalRuleCall_2_0; }

		//"longitude"
		public Keyword getLongitudeKeyword_3() { return cLongitudeKeyword_3; }

		//longitude=STRING
		public Assignment getLongitudeAssignment_4() { return cLongitudeAssignment_4; }

		//STRING
		public RuleCall getLongitudeSTRINGTerminalRuleCall_4_0() { return cLongitudeSTRINGTerminalRuleCall_4_0; }

		//"region"
		public Keyword getRegionKeyword_5() { return cRegionKeyword_5; }

		//region=STRING
		public Assignment getRegionAssignment_6() { return cRegionAssignment_6; }

		//STRING
		public RuleCall getRegionSTRINGTerminalRuleCall_6_0() { return cRegionSTRINGTerminalRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class UpdateFreqElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "UpdateFreq");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cUpdateFreqKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTimeKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTimeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTimeINTTerminalRuleCall_2_0 = (RuleCall)cTimeAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		
		//UpdateFreq:
		//	"UpdateFreq {" "time" time=INT "}";
		public ParserRule getRule() { return rule; }

		//"UpdateFreq {" "time" time=INT "}"
		public Group getGroup() { return cGroup; }

		//"UpdateFreq {"
		public Keyword getUpdateFreqKeyword_0() { return cUpdateFreqKeyword_0; }

		//"time"
		public Keyword getTimeKeyword_1() { return cTimeKeyword_1; }

		//time=INT
		public Assignment getTimeAssignment_2() { return cTimeAssignment_2; }

		//INT
		public RuleCall getTimeINTTerminalRuleCall_2_0() { return cTimeINTTerminalRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }
	}

	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Data");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cNumberParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTextParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cImageParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cVideoParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cPostParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		private final Group cGroup_5 = (Group)cAlternatives.eContents().get(5);
		private final Keyword cDataKeyword_5_0 = (Keyword)cGroup_5.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_5_1 = (Keyword)cGroup_5.eContents().get(1);
		private final Assignment cMetadataAssignment_5_2 = (Assignment)cGroup_5.eContents().get(2);
		private final RuleCall cMetadataMetadataParserRuleCall_5_2_0 = (RuleCall)cMetadataAssignment_5_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5_3 = (Keyword)cGroup_5.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_5_4 = (Keyword)cGroup_5.eContents().get(4);
		
		//Data:
		//	Number | Text | Image | Video | Post | "Data {" "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//Number | Text | Image | Video | Post | "Data {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Alternatives getAlternatives() { return cAlternatives; }

		//Number
		public RuleCall getNumberParserRuleCall_0() { return cNumberParserRuleCall_0; }

		//Text
		public RuleCall getTextParserRuleCall_1() { return cTextParserRuleCall_1; }

		//Image
		public RuleCall getImageParserRuleCall_2() { return cImageParserRuleCall_2; }

		//Video
		public RuleCall getVideoParserRuleCall_3() { return cVideoParserRuleCall_3; }

		//Post
		public RuleCall getPostParserRuleCall_4() { return cPostParserRuleCall_4; }

		//"Data {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup_5() { return cGroup_5; }

		//"Data {"
		public Keyword getDataKeyword_5_0() { return cDataKeyword_5_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_5_1() { return cMetadataInfoKeyword_5_1; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_5_2() { return cMetadataAssignment_5_2; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_5_2_0() { return cMetadataMetadataParserRuleCall_5_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_3() { return cRightCurlyBracketKeyword_5_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5_4() { return cRightCurlyBracketKeyword_5_4; }
	}

	public class NumberElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Number");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSocialNetworkCheckinsParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cCellphoneDensityParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Number:
		//	SocialNetworkCheckins | CellphoneDensity;
		public ParserRule getRule() { return rule; }

		//SocialNetworkCheckins | CellphoneDensity
		public Alternatives getAlternatives() { return cAlternatives; }

		//SocialNetworkCheckins
		public RuleCall getSocialNetworkCheckinsParserRuleCall_0() { return cSocialNetworkCheckinsParserRuleCall_0; }

		//CellphoneDensity
		public RuleCall getCellphoneDensityParserRuleCall_1() { return cCellphoneDensityParserRuleCall_1; }
	}

	public class SocialNetworkCheckinsElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SocialNetworkCheckins");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSocialNetworkCheckinsKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cAmountKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cAmountAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cAmountINTTerminalRuleCall_2_0 = (RuleCall)cAmountAssignment_2.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMetadataAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMetadataMetadataParserRuleCall_4_0 = (RuleCall)cMetadataAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//SocialNetworkCheckins:
		//	"SocialNetworkCheckins {" "amount" amount=INT "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"SocialNetworkCheckins {" "amount" amount=INT "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"SocialNetworkCheckins {"
		public Keyword getSocialNetworkCheckinsKeyword_0() { return cSocialNetworkCheckinsKeyword_0; }

		//"amount"
		public Keyword getAmountKeyword_1() { return cAmountKeyword_1; }

		//amount=INT
		public Assignment getAmountAssignment_2() { return cAmountAssignment_2; }

		//INT
		public RuleCall getAmountINTTerminalRuleCall_2_0() { return cAmountINTTerminalRuleCall_2_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_3() { return cMetadataInfoKeyword_3; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_4() { return cMetadataAssignment_4; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_4_0() { return cMetadataMetadataParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class CellphoneDensityElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CellphoneDensity");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cCellphoneDensityKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMeasureKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMeasureAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMeasureINTTerminalRuleCall_2_0 = (RuleCall)cMeasureAssignment_2.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cMetadataAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cMetadataMetadataParserRuleCall_4_0 = (RuleCall)cMetadataAssignment_4.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		
		//CellphoneDensity:
		//	"CellphoneDensity {" "measure" measure=INT "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"CellphoneDensity {" "measure" measure=INT "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"CellphoneDensity {"
		public Keyword getCellphoneDensityKeyword_0() { return cCellphoneDensityKeyword_0; }

		//"measure"
		public Keyword getMeasureKeyword_1() { return cMeasureKeyword_1; }

		//measure=INT
		public Assignment getMeasureAssignment_2() { return cMeasureAssignment_2; }

		//INT
		public RuleCall getMeasureINTTerminalRuleCall_2_0() { return cMeasureINTTerminalRuleCall_2_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_3() { return cMetadataInfoKeyword_3; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_4() { return cMetadataAssignment_4; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_4_0() { return cMetadataMetadataParserRuleCall_4_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }
	}

	public class TextElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Text");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cMeteoDataParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cTrafficSensorParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cTransportScheduleParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cAlertParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		private final RuleCall cParagraphParserRuleCall_4 = (RuleCall)cAlternatives.eContents().get(4);
		
		//Text:
		//	MeteoData | TrafficSensor | TransportSchedule | Alert | Paragraph;
		public ParserRule getRule() { return rule; }

		//MeteoData | TrafficSensor | TransportSchedule | Alert | Paragraph
		public Alternatives getAlternatives() { return cAlternatives; }

		//MeteoData
		public RuleCall getMeteoDataParserRuleCall_0() { return cMeteoDataParserRuleCall_0; }

		//TrafficSensor
		public RuleCall getTrafficSensorParserRuleCall_1() { return cTrafficSensorParserRuleCall_1; }

		//TransportSchedule
		public RuleCall getTransportScheduleParserRuleCall_2() { return cTransportScheduleParserRuleCall_2; }

		//Alert
		public RuleCall getAlertParserRuleCall_3() { return cAlertParserRuleCall_3; }

		//Paragraph
		public RuleCall getParagraphParserRuleCall_4() { return cParagraphParserRuleCall_4; }
	}

	public class ParagraphElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Paragraph");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cParagraphKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cDataAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cDataSTRINGTerminalRuleCall_1_0 = (RuleCall)cDataAssignment_1.eContents().get(0);
		
		//Paragraph:
		//	"Paragraph " data=STRING;
		public ParserRule getRule() { return rule; }

		//"Paragraph " data=STRING
		public Group getGroup() { return cGroup; }

		//"Paragraph "
		public Keyword getParagraphKeyword_0() { return cParagraphKeyword_0; }

		//data=STRING
		public Assignment getDataAssignment_1() { return cDataAssignment_1; }

		//STRING
		public RuleCall getDataSTRINGTerminalRuleCall_1_0() { return cDataSTRINGTerminalRuleCall_1_0; }
	}

	public class MeteoDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "MeteoData");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cMeteoDataKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMetadataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMetadataMetadataParserRuleCall_2_0 = (RuleCall)cMetadataAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//MeteoData:
		//	"MeteoData {" "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"MeteoData {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"MeteoData {"
		public Keyword getMeteoDataKeyword_0() { return cMeteoDataKeyword_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_1() { return cMetadataInfoKeyword_1; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_2() { return cMetadataAssignment_2; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_2_0() { return cMetadataMetadataParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class TrafficSensorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TrafficSensor");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTrafficSensorKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMetadataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMetadataMetadataParserRuleCall_2_0 = (RuleCall)cMetadataAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TrafficSensor:
		//	"TrafficSensor {" "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"TrafficSensor {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"TrafficSensor {"
		public Keyword getTrafficSensorKeyword_0() { return cTrafficSensorKeyword_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_1() { return cMetadataInfoKeyword_1; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_2() { return cMetadataAssignment_2; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_2_0() { return cMetadataMetadataParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class TransportScheduleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "TransportSchedule");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransportScheduleKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMetadataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMetadataMetadataParserRuleCall_2_0 = (RuleCall)cMetadataAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//TransportSchedule:
		//	"TransportSchedule {" "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"TransportSchedule {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"TransportSchedule {"
		public Keyword getTransportScheduleKeyword_0() { return cTransportScheduleKeyword_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_1() { return cMetadataInfoKeyword_1; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_2() { return cMetadataAssignment_2; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_2_0() { return cMetadataMetadataParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class AlertElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Alert");
		private final RuleCall cPublicAlertParserRuleCall = (RuleCall)rule.eContents().get(1);
		
		//Alert:
		//	PublicAlert;
		public ParserRule getRule() { return rule; }

		//PublicAlert
		public RuleCall getPublicAlertParserRuleCall() { return cPublicAlertParserRuleCall; }
	}

	public class PublicAlertElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "PublicAlert");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cPublicAlertKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMetadataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMetadataMetadataParserRuleCall_2_0 = (RuleCall)cMetadataAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//PublicAlert:
		//	"PublicAlert {" "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"PublicAlert {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"PublicAlert {"
		public Keyword getPublicAlertKeyword_0() { return cPublicAlertKeyword_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_1() { return cMetadataInfoKeyword_1; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_2() { return cMetadataAssignment_2; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_2_0() { return cMetadataMetadataParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class PostElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Post");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cTwitterParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cFacebookParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cBlogParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cInstagramParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//Post:
		//	Twitter | Facebook | Blog | Instagram;
		public ParserRule getRule() { return rule; }

		//Twitter | Facebook | Blog | Instagram
		public Alternatives getAlternatives() { return cAlternatives; }

		//Twitter
		public RuleCall getTwitterParserRuleCall_0() { return cTwitterParserRuleCall_0; }

		//Facebook
		public RuleCall getFacebookParserRuleCall_1() { return cFacebookParserRuleCall_1; }

		//Blog
		public RuleCall getBlogParserRuleCall_2() { return cBlogParserRuleCall_2; }

		//Instagram
		public RuleCall getInstagramParserRuleCall_3() { return cInstagramParserRuleCall_3; }
	}

	public class TwitterElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Twitter");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTwitterKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTextsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cParagraphsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cParagraphsParagraphParserRuleCall_2_0 = (RuleCall)cParagraphsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cImagesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cImagesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cImagesImageParserRuleCall_5_0 = (RuleCall)cImagesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cVideosKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cVideosAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cVideosWebVideoParserRuleCall_8_0 = (RuleCall)cVideosAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cMetadataInfoKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMetadataAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMetadataMetadataParserRuleCall_11_0 = (RuleCall)cMetadataAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Twitter:
		//	"Twitter {" "texts {" paragraphs+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
		//	"metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"Twitter {" "texts {" paragraphs+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
		//"metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"Twitter {"
		public Keyword getTwitterKeyword_0() { return cTwitterKeyword_0; }

		//"texts {"
		public Keyword getTextsKeyword_1() { return cTextsKeyword_1; }

		//paragraphs+=Paragraph*
		public Assignment getParagraphsAssignment_2() { return cParagraphsAssignment_2; }

		//Paragraph
		public RuleCall getParagraphsParagraphParserRuleCall_2_0() { return cParagraphsParagraphParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"images {"
		public Keyword getImagesKeyword_4() { return cImagesKeyword_4; }

		//images+=Image*
		public Assignment getImagesAssignment_5() { return cImagesAssignment_5; }

		//Image
		public RuleCall getImagesImageParserRuleCall_5_0() { return cImagesImageParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//"videos {"
		public Keyword getVideosKeyword_7() { return cVideosKeyword_7; }

		//videos+=WebVideo*
		public Assignment getVideosAssignment_8() { return cVideosAssignment_8; }

		//WebVideo
		public RuleCall getVideosWebVideoParserRuleCall_8_0() { return cVideosWebVideoParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_10() { return cMetadataInfoKeyword_10; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_11() { return cMetadataAssignment_11; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_11_0() { return cMetadataMetadataParserRuleCall_11_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class BlogElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Blog");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cBlogKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTextsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextsParagraphParserRuleCall_2_0 = (RuleCall)cTextsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cImagesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cImagesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cImagesImageParserRuleCall_5_0 = (RuleCall)cImagesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cVideosKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cVideosAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cVideosWebVideoParserRuleCall_8_0 = (RuleCall)cVideosAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cMetadataInfoKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMetadataAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMetadataMetadataParserRuleCall_11_0 = (RuleCall)cMetadataAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Blog:
		//	"Blog {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
		//	"metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"Blog {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}" "metadataInfo {"
		//metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"Blog {"
		public Keyword getBlogKeyword_0() { return cBlogKeyword_0; }

		//"texts {"
		public Keyword getTextsKeyword_1() { return cTextsKeyword_1; }

		//texts+=Paragraph*
		public Assignment getTextsAssignment_2() { return cTextsAssignment_2; }

		//Paragraph
		public RuleCall getTextsParagraphParserRuleCall_2_0() { return cTextsParagraphParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"images {"
		public Keyword getImagesKeyword_4() { return cImagesKeyword_4; }

		//images+=Image*
		public Assignment getImagesAssignment_5() { return cImagesAssignment_5; }

		//Image
		public RuleCall getImagesImageParserRuleCall_5_0() { return cImagesImageParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//"videos {"
		public Keyword getVideosKeyword_7() { return cVideosKeyword_7; }

		//videos+=WebVideo*
		public Assignment getVideosAssignment_8() { return cVideosAssignment_8; }

		//WebVideo
		public RuleCall getVideosWebVideoParserRuleCall_8_0() { return cVideosWebVideoParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_10() { return cMetadataInfoKeyword_10; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_11() { return cMetadataAssignment_11; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_11_0() { return cMetadataMetadataParserRuleCall_11_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class FacebookElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Facebook");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cFacebookKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTextsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextsParagraphParserRuleCall_2_0 = (RuleCall)cTextsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cImagesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cImagesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cImagesImageParserRuleCall_5_0 = (RuleCall)cImagesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cVideosKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cVideosAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cVideosWebVideoParserRuleCall_8_0 = (RuleCall)cVideosAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cMetadataInfoKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMetadataAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMetadataMetadataParserRuleCall_11_0 = (RuleCall)cMetadataAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Facebook:
		//	"Facebook {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
		//	"metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"Facebook {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
		//"metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"Facebook {"
		public Keyword getFacebookKeyword_0() { return cFacebookKeyword_0; }

		//"texts {"
		public Keyword getTextsKeyword_1() { return cTextsKeyword_1; }

		//texts+=Paragraph*
		public Assignment getTextsAssignment_2() { return cTextsAssignment_2; }

		//Paragraph
		public RuleCall getTextsParagraphParserRuleCall_2_0() { return cTextsParagraphParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"images {"
		public Keyword getImagesKeyword_4() { return cImagesKeyword_4; }

		//images+=Image*
		public Assignment getImagesAssignment_5() { return cImagesAssignment_5; }

		//Image
		public RuleCall getImagesImageParserRuleCall_5_0() { return cImagesImageParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//"videos {"
		public Keyword getVideosKeyword_7() { return cVideosKeyword_7; }

		//videos+=WebVideo*
		public Assignment getVideosAssignment_8() { return cVideosAssignment_8; }

		//WebVideo
		public RuleCall getVideosWebVideoParserRuleCall_8_0() { return cVideosWebVideoParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_10() { return cMetadataInfoKeyword_10; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_11() { return cMetadataAssignment_11; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_11_0() { return cMetadataMetadataParserRuleCall_11_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class InstagramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Instagram");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInstagramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cTextsKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cTextsAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cTextsParagraphParserRuleCall_2_0 = (RuleCall)cTextsAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cImagesKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cImagesAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cImagesImageParserRuleCall_5_0 = (RuleCall)cImagesAssignment_5.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Keyword cVideosKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cVideosAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cVideosWebVideoParserRuleCall_8_0 = (RuleCall)cVideosAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cMetadataInfoKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cMetadataAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cMetadataMetadataParserRuleCall_11_0 = (RuleCall)cMetadataAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		private final Keyword cRightCurlyBracketKeyword_13 = (Keyword)cGroup.eContents().get(13);
		
		//Instagram:
		//	"Instagram {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
		//	"metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"Instagram {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
		//"metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"Instagram {"
		public Keyword getInstagramKeyword_0() { return cInstagramKeyword_0; }

		//"texts {"
		public Keyword getTextsKeyword_1() { return cTextsKeyword_1; }

		//texts+=Paragraph*
		public Assignment getTextsAssignment_2() { return cTextsAssignment_2; }

		//Paragraph
		public RuleCall getTextsParagraphParserRuleCall_2_0() { return cTextsParagraphParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"images {"
		public Keyword getImagesKeyword_4() { return cImagesKeyword_4; }

		//images+=Image*
		public Assignment getImagesAssignment_5() { return cImagesAssignment_5; }

		//Image
		public RuleCall getImagesImageParserRuleCall_5_0() { return cImagesImageParserRuleCall_5_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_6() { return cRightCurlyBracketKeyword_6; }

		//"videos {"
		public Keyword getVideosKeyword_7() { return cVideosKeyword_7; }

		//videos+=WebVideo*
		public Assignment getVideosAssignment_8() { return cVideosAssignment_8; }

		//WebVideo
		public RuleCall getVideosWebVideoParserRuleCall_8_0() { return cVideosWebVideoParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_10() { return cMetadataInfoKeyword_10; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_11() { return cMetadataAssignment_11; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_11_0() { return cMetadataMetadataParserRuleCall_11_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_13() { return cRightCurlyBracketKeyword_13; }
	}

	public class ImageElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Image");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cImageUrlKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUrlAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUrlSTRINGTerminalRuleCall_1_0 = (RuleCall)cUrlAssignment_1.eContents().get(0);
		
		//Image:
		//	"Image url " url=STRING;
		public ParserRule getRule() { return rule; }

		//"Image url " url=STRING
		public Group getGroup() { return cGroup; }

		//"Image url "
		public Keyword getImageUrlKeyword_0() { return cImageUrlKeyword_0; }

		//url=STRING
		public Assignment getUrlAssignment_1() { return cUrlAssignment_1; }

		//STRING
		public RuleCall getUrlSTRINGTerminalRuleCall_1_0() { return cUrlSTRINGTerminalRuleCall_1_0; }
	}

	public class VideoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Video");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cCameraParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cWebVideoParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Video:
		//	Camera | WebVideo;
		public ParserRule getRule() { return rule; }

		//Camera | WebVideo
		public Alternatives getAlternatives() { return cAlternatives; }

		//Camera
		public RuleCall getCameraParserRuleCall_0() { return cCameraParserRuleCall_0; }

		//WebVideo
		public RuleCall getWebVideoParserRuleCall_1() { return cWebVideoParserRuleCall_1; }
	}

	public class WebVideoElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "WebVideo");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cWebVideoUrlKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cUrlAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cUrlSTRINGTerminalRuleCall_1_0 = (RuleCall)cUrlAssignment_1.eContents().get(0);
		
		//WebVideo:
		//	"WebVideo url " url=STRING;
		public ParserRule getRule() { return rule; }

		//"WebVideo url " url=STRING
		public Group getGroup() { return cGroup; }

		//"WebVideo url "
		public Keyword getWebVideoUrlKeyword_0() { return cWebVideoUrlKeyword_0; }

		//url=STRING
		public Assignment getUrlAssignment_1() { return cUrlAssignment_1; }

		//STRING
		public RuleCall getUrlSTRINGTerminalRuleCall_1_0() { return cUrlSTRINGTerminalRuleCall_1_0; }
	}

	public class CameraElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Camera");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSecurityCamParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cHighwayCamParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Camera:
		//	SecurityCam | HighwayCam;
		public ParserRule getRule() { return rule; }

		//SecurityCam | HighwayCam
		public Alternatives getAlternatives() { return cAlternatives; }

		//SecurityCam
		public RuleCall getSecurityCamParserRuleCall_0() { return cSecurityCamParserRuleCall_0; }

		//HighwayCam
		public RuleCall getHighwayCamParserRuleCall_1() { return cHighwayCamParserRuleCall_1; }
	}

	public class HighwayCamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "HighwayCam");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHighwayCamKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMetadataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMetadataMetadataParserRuleCall_2_0 = (RuleCall)cMetadataAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//HighwayCam:
		//	"HighwayCam {" "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"HighwayCam {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"HighwayCam {"
		public Keyword getHighwayCamKeyword_0() { return cHighwayCamKeyword_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_1() { return cMetadataInfoKeyword_1; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_2() { return cMetadataAssignment_2; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_2_0() { return cMetadataMetadataParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class SecurityCamElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SecurityCam");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSecurityCamKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cMetadataInfoKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cMetadataAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cMetadataMetadataParserRuleCall_2_0 = (RuleCall)cMetadataAssignment_2.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//SecurityCam:
		//	"SecurityCam {" "metadataInfo {" metadata+=Metadata+ "}" "}";
		public ParserRule getRule() { return rule; }

		//"SecurityCam {" "metadataInfo {" metadata+=Metadata+ "}" "}"
		public Group getGroup() { return cGroup; }

		//"SecurityCam {"
		public Keyword getSecurityCamKeyword_0() { return cSecurityCamKeyword_0; }

		//"metadataInfo {"
		public Keyword getMetadataInfoKeyword_1() { return cMetadataInfoKeyword_1; }

		//metadata+=Metadata+
		public Assignment getMetadataAssignment_2() { return cMetadataAssignment_2; }

		//Metadata
		public RuleCall getMetadataMetadataParserRuleCall_2_0() { return cMetadataMetadataParserRuleCall_2_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3() { return cRightCurlyBracketKeyword_3; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}
	
	
	private SmartCityElements pSmartCity;
	private ProviderElements pProvider;
	private NewsSiteElements pNewsSite;
	private HighwayElements pHighway;
	private PublicTransportElements pPublicTransport;
	private ProvinceElements pProvince;
	private CountyElements pCounty;
	private MunicipalityElements pMunicipality;
	private DataSourceElements pDataSource;
	private MetadataElements pMetadata;
	private IssuedDateElements pIssuedDate;
	private LocationElements pLocation;
	private UpdateFreqElements pUpdateFreq;
	private DataElements pData;
	private NumberElements pNumber;
	private SocialNetworkCheckinsElements pSocialNetworkCheckins;
	private CellphoneDensityElements pCellphoneDensity;
	private TextElements pText;
	private ParagraphElements pParagraph;
	private MeteoDataElements pMeteoData;
	private TrafficSensorElements pTrafficSensor;
	private TransportScheduleElements pTransportSchedule;
	private AlertElements pAlert;
	private PublicAlertElements pPublicAlert;
	private PostElements pPost;
	private TwitterElements pTwitter;
	private BlogElements pBlog;
	private FacebookElements pFacebook;
	private InstagramElements pInstagram;
	private ImageElements pImage;
	private VideoElements pVideo;
	private WebVideoElements pWebVideo;
	private CameraElements pCamera;
	private HighwayCamElements pHighwayCam;
	private SecurityCamElements pSecurityCam;
	
	private final Grammar grammar;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public SmartCityGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("com.polimi.ase.concretesyntax.xtext.SmartCity".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	////import "platform:/resource/com.polimi.ase.smartcity_b/model/SmartCity.ecore"
	// //extension 'scity'
	// SmartCity:
	//	providers+=Provider+ dataSources+=DataSource*;
	public SmartCityElements getSmartCityAccess() {
		return (pSmartCity != null) ? pSmartCity : (pSmartCity = new SmartCityElements());
	}
	
	public ParserRule getSmartCityRule() {
		return getSmartCityAccess().getRule();
	}

	//Provider:
	//	NewsSite | Highway | PublicTransport | Province | County | Municipality;
	public ProviderElements getProviderAccess() {
		return (pProvider != null) ? pProvider : (pProvider = new ProviderElements());
	}
	
	public ParserRule getProviderRule() {
		return getProviderAccess().getRule();
	}

	//NewsSite:
	//	"NewsSite " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
	public NewsSiteElements getNewsSiteAccess() {
		return (pNewsSite != null) ? pNewsSite : (pNewsSite = new NewsSiteElements());
	}
	
	public ParserRule getNewsSiteRule() {
		return getNewsSiteAccess().getRule();
	}

	//Highway:
	//	"Highway " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
	public HighwayElements getHighwayAccess() {
		return (pHighway != null) ? pHighway : (pHighway = new HighwayElements());
	}
	
	public ParserRule getHighwayRule() {
		return getHighwayAccess().getRule();
	}

	//PublicTransport:
	//	"PublicTransport " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
	public PublicTransportElements getPublicTransportAccess() {
		return (pPublicTransport != null) ? pPublicTransport : (pPublicTransport = new PublicTransportElements());
	}
	
	public ParserRule getPublicTransportRule() {
		return getPublicTransportAccess().getRule();
	}

	//Province:
	//	"Province " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
	public ProvinceElements getProvinceAccess() {
		return (pProvince != null) ? pProvince : (pProvince = new ProvinceElements());
	}
	
	public ParserRule getProvinceRule() {
		return getProvinceAccess().getRule();
	}

	//County:
	//	"County " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
	public CountyElements getCountyAccess() {
		return (pCounty != null) ? pCounty : (pCounty = new CountyElements());
	}
	
	public ParserRule getCountyRule() {
		return getCountyAccess().getRule();
	}

	//Municipality:
	//	"Municipality " name=ID " {" "sources " sources+=[DataSource] ("," sources+=[DataSource])* "}";
	public MunicipalityElements getMunicipalityAccess() {
		return (pMunicipality != null) ? pMunicipality : (pMunicipality = new MunicipalityElements());
	}
	
	public ParserRule getMunicipalityRule() {
		return getMunicipalityAccess().getRule();
	}

	//DataSource:
	//	"DataSource " name=ID " {" data+=Data+ "}";
	public DataSourceElements getDataSourceAccess() {
		return (pDataSource != null) ? pDataSource : (pDataSource = new DataSourceElements());
	}
	
	public ParserRule getDataSourceRule() {
		return getDataSourceAccess().getRule();
	}

	//Metadata:
	//	Location | UpdateFreq | IssuedDate;
	public MetadataElements getMetadataAccess() {
		return (pMetadata != null) ? pMetadata : (pMetadata = new MetadataElements());
	}
	
	public ParserRule getMetadataRule() {
		return getMetadataAccess().getRule();
	}

	//IssuedDate:
	//	"IssuedDate {" "date" date=STRING "}";
	public IssuedDateElements getIssuedDateAccess() {
		return (pIssuedDate != null) ? pIssuedDate : (pIssuedDate = new IssuedDateElements());
	}
	
	public ParserRule getIssuedDateRule() {
		return getIssuedDateAccess().getRule();
	}

	//Location:
	//	"Location {" "latitude" latitude=STRING "longitude" longitude=STRING "region" region=STRING "}";
	public LocationElements getLocationAccess() {
		return (pLocation != null) ? pLocation : (pLocation = new LocationElements());
	}
	
	public ParserRule getLocationRule() {
		return getLocationAccess().getRule();
	}

	//UpdateFreq:
	//	"UpdateFreq {" "time" time=INT "}";
	public UpdateFreqElements getUpdateFreqAccess() {
		return (pUpdateFreq != null) ? pUpdateFreq : (pUpdateFreq = new UpdateFreqElements());
	}
	
	public ParserRule getUpdateFreqRule() {
		return getUpdateFreqAccess().getRule();
	}

	//Data:
	//	Number | Text | Image | Video | Post | "Data {" "metadataInfo {" metadata+=Metadata+ "}" "}";
	public DataElements getDataAccess() {
		return (pData != null) ? pData : (pData = new DataElements());
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}

	//Number:
	//	SocialNetworkCheckins | CellphoneDensity;
	public NumberElements getNumberAccess() {
		return (pNumber != null) ? pNumber : (pNumber = new NumberElements());
	}
	
	public ParserRule getNumberRule() {
		return getNumberAccess().getRule();
	}

	//SocialNetworkCheckins:
	//	"SocialNetworkCheckins {" "amount" amount=INT "metadataInfo {" metadata+=Metadata+ "}" "}";
	public SocialNetworkCheckinsElements getSocialNetworkCheckinsAccess() {
		return (pSocialNetworkCheckins != null) ? pSocialNetworkCheckins : (pSocialNetworkCheckins = new SocialNetworkCheckinsElements());
	}
	
	public ParserRule getSocialNetworkCheckinsRule() {
		return getSocialNetworkCheckinsAccess().getRule();
	}

	//CellphoneDensity:
	//	"CellphoneDensity {" "measure" measure=INT "metadataInfo {" metadata+=Metadata+ "}" "}";
	public CellphoneDensityElements getCellphoneDensityAccess() {
		return (pCellphoneDensity != null) ? pCellphoneDensity : (pCellphoneDensity = new CellphoneDensityElements());
	}
	
	public ParserRule getCellphoneDensityRule() {
		return getCellphoneDensityAccess().getRule();
	}

	//Text:
	//	MeteoData | TrafficSensor | TransportSchedule | Alert | Paragraph;
	public TextElements getTextAccess() {
		return (pText != null) ? pText : (pText = new TextElements());
	}
	
	public ParserRule getTextRule() {
		return getTextAccess().getRule();
	}

	//Paragraph:
	//	"Paragraph " data=STRING;
	public ParagraphElements getParagraphAccess() {
		return (pParagraph != null) ? pParagraph : (pParagraph = new ParagraphElements());
	}
	
	public ParserRule getParagraphRule() {
		return getParagraphAccess().getRule();
	}

	//MeteoData:
	//	"MeteoData {" "metadataInfo {" metadata+=Metadata+ "}" "}";
	public MeteoDataElements getMeteoDataAccess() {
		return (pMeteoData != null) ? pMeteoData : (pMeteoData = new MeteoDataElements());
	}
	
	public ParserRule getMeteoDataRule() {
		return getMeteoDataAccess().getRule();
	}

	//TrafficSensor:
	//	"TrafficSensor {" "metadataInfo {" metadata+=Metadata+ "}" "}";
	public TrafficSensorElements getTrafficSensorAccess() {
		return (pTrafficSensor != null) ? pTrafficSensor : (pTrafficSensor = new TrafficSensorElements());
	}
	
	public ParserRule getTrafficSensorRule() {
		return getTrafficSensorAccess().getRule();
	}

	//TransportSchedule:
	//	"TransportSchedule {" "metadataInfo {" metadata+=Metadata+ "}" "}";
	public TransportScheduleElements getTransportScheduleAccess() {
		return (pTransportSchedule != null) ? pTransportSchedule : (pTransportSchedule = new TransportScheduleElements());
	}
	
	public ParserRule getTransportScheduleRule() {
		return getTransportScheduleAccess().getRule();
	}

	//Alert:
	//	PublicAlert;
	public AlertElements getAlertAccess() {
		return (pAlert != null) ? pAlert : (pAlert = new AlertElements());
	}
	
	public ParserRule getAlertRule() {
		return getAlertAccess().getRule();
	}

	//PublicAlert:
	//	"PublicAlert {" "metadataInfo {" metadata+=Metadata+ "}" "}";
	public PublicAlertElements getPublicAlertAccess() {
		return (pPublicAlert != null) ? pPublicAlert : (pPublicAlert = new PublicAlertElements());
	}
	
	public ParserRule getPublicAlertRule() {
		return getPublicAlertAccess().getRule();
	}

	//Post:
	//	Twitter | Facebook | Blog | Instagram;
	public PostElements getPostAccess() {
		return (pPost != null) ? pPost : (pPost = new PostElements());
	}
	
	public ParserRule getPostRule() {
		return getPostAccess().getRule();
	}

	//Twitter:
	//	"Twitter {" "texts {" paragraphs+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
	//	"metadataInfo {" metadata+=Metadata+ "}" "}";
	public TwitterElements getTwitterAccess() {
		return (pTwitter != null) ? pTwitter : (pTwitter = new TwitterElements());
	}
	
	public ParserRule getTwitterRule() {
		return getTwitterAccess().getRule();
	}

	//Blog:
	//	"Blog {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
	//	"metadataInfo {" metadata+=Metadata+ "}" "}";
	public BlogElements getBlogAccess() {
		return (pBlog != null) ? pBlog : (pBlog = new BlogElements());
	}
	
	public ParserRule getBlogRule() {
		return getBlogAccess().getRule();
	}

	//Facebook:
	//	"Facebook {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
	//	"metadataInfo {" metadata+=Metadata+ "}" "}";
	public FacebookElements getFacebookAccess() {
		return (pFacebook != null) ? pFacebook : (pFacebook = new FacebookElements());
	}
	
	public ParserRule getFacebookRule() {
		return getFacebookAccess().getRule();
	}

	//Instagram:
	//	"Instagram {" "texts {" texts+=Paragraph* "}" "images {" images+=Image* "}" "videos {" videos+=WebVideo* "}"
	//	"metadataInfo {" metadata+=Metadata+ "}" "}";
	public InstagramElements getInstagramAccess() {
		return (pInstagram != null) ? pInstagram : (pInstagram = new InstagramElements());
	}
	
	public ParserRule getInstagramRule() {
		return getInstagramAccess().getRule();
	}

	//Image:
	//	"Image url " url=STRING;
	public ImageElements getImageAccess() {
		return (pImage != null) ? pImage : (pImage = new ImageElements());
	}
	
	public ParserRule getImageRule() {
		return getImageAccess().getRule();
	}

	//Video:
	//	Camera | WebVideo;
	public VideoElements getVideoAccess() {
		return (pVideo != null) ? pVideo : (pVideo = new VideoElements());
	}
	
	public ParserRule getVideoRule() {
		return getVideoAccess().getRule();
	}

	//WebVideo:
	//	"WebVideo url " url=STRING;
	public WebVideoElements getWebVideoAccess() {
		return (pWebVideo != null) ? pWebVideo : (pWebVideo = new WebVideoElements());
	}
	
	public ParserRule getWebVideoRule() {
		return getWebVideoAccess().getRule();
	}

	//Camera:
	//	SecurityCam | HighwayCam;
	public CameraElements getCameraAccess() {
		return (pCamera != null) ? pCamera : (pCamera = new CameraElements());
	}
	
	public ParserRule getCameraRule() {
		return getCameraAccess().getRule();
	}

	//HighwayCam:
	//	"HighwayCam {" "metadataInfo {" metadata+=Metadata+ "}" "}";
	public HighwayCamElements getHighwayCamAccess() {
		return (pHighwayCam != null) ? pHighwayCam : (pHighwayCam = new HighwayCamElements());
	}
	
	public ParserRule getHighwayCamRule() {
		return getHighwayCamAccess().getRule();
	}

	//SecurityCam:
	//	"SecurityCam {" "metadataInfo {" metadata+=Metadata+ "}" "}";
	public SecurityCamElements getSecurityCamAccess() {
		return (pSecurityCam != null) ? pSecurityCam : (pSecurityCam = new SecurityCamElements());
	}
	
	public ParserRule getSecurityCamRule() {
		return getSecurityCamAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
