/*
* generated by Xtext
*/
package com.polimi.ase.concretesyntax.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SmartCityAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/polimi/ase/concretesyntax/xtext/parser/antlr/internal/InternalSmartCity.tokens");
	}
}
