/*
* generated by Xtext
*/
package com.polimi.ase.concretesyntax.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.polimi.ase.concretesyntax.xtext.services.SmartCityGrammarAccess;

public class SmartCityParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SmartCityGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.polimi.ase.concretesyntax.xtext.parser.antlr.internal.InternalSmartCityParser createParser(XtextTokenStream stream) {
		return new com.polimi.ase.concretesyntax.xtext.parser.antlr.internal.InternalSmartCityParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "SmartCity";
	}
	
	public SmartCityGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SmartCityGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
