/**
 * generated by Xtext
 */
package com.polimi.ase.concretesyntax.xtext.validation;

import com.polimi.ase.concretesyntax.xtext.validation.AbstractSmartCityValidator;

/**
 * Custom validation rules.
 * 
 * see http://www.eclipse.org/Xtext/documentation.html#validation
 */
@SuppressWarnings("all")
public class SmartCityValidator extends AbstractSmartCityValidator {
}
