/**
 * generated by Xtext
 */
package com.polimi.ase.concretesyntax.xtext.ui.contentassist;

import com.polimi.ase.concretesyntax.xtext.ui.contentassist.AbstractSmartCityProposalProvider;

/**
 * see http://www.eclipse.org/Xtext/documentation.html#contentAssist on how to customize content assistant
 */
@SuppressWarnings("all")
public class SmartCityProposalProvider extends AbstractSmartCityProposalProvider {
}
