/*
* generated by Xtext
*/
package com.polimi.ase.concretesyntax.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SmartCityStandaloneSetup extends SmartCityStandaloneSetupGenerated{

	public static void doSetup() {
		new SmartCityStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

