/*
 * generated by Xtext
 */
package com.polimi.ase.concretesyntax.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SmartCityRuntimeModule extends com.polimi.ase.concretesyntax.xtext.AbstractSmartCityRuntimeModule {

}
